SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800

STICKY_LAYOUT = ""
TITLE_FONT_SIZE = 70
LOGO_WIDTH = 400
LOGO_HEIGHT = 200

GENERAL_FONT = "Ariel"

FORGOT_PSWD_WIDTH = 300
FORGOT_PSWD_HEIGHT = 60
FORGOT_PSWD_FONT = (GENERAL_FONT, 20)

ENTRY_WIDTH = 200
ENTRY_HEIGHT = 30
ENTRY_FONT = (GENERAL_FONT, 25)


LOGIN_BTN_WIDTH = 300
LOGIN_BTN_HEIGHT = 60
LOGIN_BTN_FONT = (GENERAL_FONT, 30)

LOGIN_Y_PADDING = 10
LOGIN_X_PADDING = 50

SIGN_UP_ERROR_PADY = 1
LOGIN_ERROR_PADY = 1

SIGNUP_Y_PADDING = 10
SIGNUP_X_PADDING = 50

MID_COL_SPAN_SIGNUP = 2

DIST_FROM_LOGO = 100

# Colors
BG_COLOR = "#353438"

CONNECTED_TEXT = "Connected"
CONNECTED_COLOR = "green"
DISCONNECTED_TEXT = "Disconnected"
DISCONNECTED_COLOR = "red"