SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800

STICKY_LAYOUT = "nsew"
TITLE_FONT_SIZE = 90
LOGO_WIDTH = 600
LOGO_HEIGHT = 200

GENERAL_FONT = "Ariel"

FORGOT_PSWD_WIDTH = 300
FORGOT_PSWD_HEIGHT = 60
FORGOT_PSWD_FONT = (GENERAL_FONT, 20)

ENTRY_WIDTH = 300
ENTRY_HEIGHT = 45
ENTRY_FONT = (GENERAL_FONT, 25)

LOGIN_BTN_WIDTH = 300
LOGIN_BTN_HEIGHT = 60
LOGIN_BTN_FONT = (GENERAL_FONT, 30)

SIGN_UP_ERROR_PADY = 2
